@startuml
skinparam componentStyle uml2

component "Панель управления" as UI
component "WebSocket Адаптер" as WS
component "Калибровка" as CALIB
component "Компонент видеозахвата" as CAPTURE
component "Компьютерное зрение" as CV

UI --> WS : команды
WS --> UI : данные визуализации

WS --> CALIB : команды
CALIB --> WS : данные визуализации

WS --> CV : команды
CV --> WS : данные визуализации

CAPTURE --> CALIB : видеопоток
CAPTURE --> CV : видеопоток
CALIB --> CV : результаты калибровки

@enduml